/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on Mar 4, 2011, 9:53:52 PM
 */

package pikater.gui.java.improved;

import jade.gui.GuiAgent;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.net.URL;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.ResourceBundle;
import javax.help.CSH;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import pikater.DataManagerService;
import pikater.ontology.messages.Task;

/**
 *
 * @author martin
 */
public class MainWindow extends javax.swing.JFrame {

    GuiAgent myAgent;

    ResultsBrowserFrame rbf;
    NewExperimentFrame nef;
    TableColumnAdjuster tca;
    FileImportProgressDialog fipd = null;
    Thread fipdThread = null;
    ArrayList<Integer> experimentOptions = new ArrayList<Integer>();

    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
    }

    public MainWindow(GuiAgent myAgent) {
        this.myAgent = myAgent;
        rbf = new ResultsBrowserFrame(myAgent);
        nef = new NewExperimentFrame(this, true, myAgent);
        initComponents();
        logTable.getColumnModel().getColumn(0).setHeaderValue(ResourceBundle.getBundle("pikater/gui/java/improved/Strings").getString("LOG_TIME"));
        logTable.getColumnModel().getColumn(1).setHeaderValue(ResourceBundle.getBundle("pikater/gui/java/improved/Strings").getString("LOG_EVENT"));
        tca = new TableColumnAdjuster(logTable);
    }

    public DataInputFrame getDataInputDialog() {
        return rbf.getDataInputDialog();
    }

    public void showFileImportProgress(int completed, int all) {

        if (all == 0)
            return;
        if (fipd == null) {
            fipd = new FileImportProgressDialog(this, true);
            fipd.setMax(all);
            fipd.setValue(completed);
            fipdThread = new Thread(new Runnable() {
                public void run() {
                    fipd.setVisible(true);
                }
            });
            fipdThread.start();
        }
        else {
            fipd.setValue(completed);
            if (completed == all) {
                fipd.setVisible(false);
                try {
                    fipdThread.join();
                }
                catch (InterruptedException ie) {
                    ie.printStackTrace();
                }
            }
        }

    }

    public void showInfo(String info) {
        String infoText = "<html><body><font color = green>" + info + "<br></font></body></html>";
        String date = "<html><body><font color = green>" + DateFormat.getDateTimeInstance(DateFormat.SHORT, DateFormat.SHORT).format(new Date()) + "<br></font></body></html>";
        DefaultTableModel dtm = (DefaultTableModel)logTable.getModel();
        Object[] row = {date, infoText};
        dtm.addRow(row);
        tca.adjustColumns();
    }

    public void showError(String error) {
        String infoText = "<html><body><font color = red>" + error + "<br></font></body></html>";
        String date = "<html><body><font color = red>" + DateFormat.getDateTimeInstance(DateFormat.SHORT, DateFormat.SHORT).format(new Date()) + "<br></font></body></html>";
        DefaultTableModel dtm = (DefaultTableModel)logTable.getModel();
        Object[] row = {date, infoText};
        dtm.addRow(row);
        tca.adjustColumns();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jToolBar1 = new javax.swing.JToolBar();
        resultsBrowserButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        logTable = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BANG 1.0");
        setMinimumSize(getPreferredSize());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pikater/gui/java/improved/Strings"); // NOI18N
        resultsBrowserButton.setText(bundle.getString("RESULTS_BROWSER")); // NOI18N
        resultsBrowserButton.setFocusable(false);
        resultsBrowserButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resultsBrowserButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        resultsBrowserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsBrowserButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(resultsBrowserButton);

        jButton2.setText(bundle.getString("FILE_BROWSER")); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton1.setText(bundle.getString("NEW_EXPERIMENT")); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("LOG_BORDER_TITLE"))); // NOI18N

        logTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(logTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        fileMenu.setText(bundle.getString("FILE")); // NOI18N

        openMenuItem.setText(bundle.getString("OPEN")); // NOI18N
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        exitMenuItem.setText(bundle.getString("EXIT")); // NOI18N
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(bundle.getString("HELP")); // NOI18N

        contentsMenuItem.setText(bundle.getString("CONTENTS")); // NOI18N
        contentsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentsMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setText(bundle.getString("ABOUT")); // NOI18N
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FileBrowserFrame fileBrowserFrame = new FileBrowserFrame(myAgent);
        fileBrowserFrame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void resultsBrowserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsBrowserButtonActionPerformed
        rbf.setVisible(true);
    }//GEN-LAST:event_resultsBrowserButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        nef = new NewExperimentFrame(this, true, myAgent);
        nef.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        DataManagerService.deleteTempFiles(myAgent);
    }//GEN-LAST:event_formWindowClosing

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        AboutDialog ad = new AboutDialog(this, false);
        ad.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter fnf = new FileNameExtensionFilter("XML Files (*.bxml)", "bxml");
        jfc.setFileFilter(fnf);

        int result = jfc.showOpenDialog(this);

        if (result == JFileChooser.CANCEL_OPTION) {
            return;
        }
        
        nef = new NewExperimentFrame(this, true, myAgent);
        System.out.println("xml file: "+jfc.getSelectedFile());
        nef.loadXML(jfc.getSelectedFile());
        nef.setVisible(true);

    }//GEN-LAST:event_openMenuItemActionPerformed

    private void contentsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentsMenuItemActionPerformed
        
        String helpHS = "BANGHelp.hs";
        ClassLoader cl = ClassLoader.getSystemClassLoader();
        HelpSet hs = null;
        try {
            URL hsURL = HelpSet.findHelpSet(cl, helpHS);
            hs = new HelpSet(null, hsURL);
        } catch (Exception ee) {
        // Say what the exception really is
            ee.printStackTrace();
            System.out.println( "HelpSet " + ee.getMessage());
            System.out.println("HelpSet "+ helpHS +" not found");
        return;
        }
        // Create a HelpBroker object:
        HelpBroker hb = hs.createHelpBroker();
        // Create a "Help" menu item to trigger the help viewer:
        hb.setDisplayed(true);

    }//GEN-LAST:event_contentsMenuItemActionPerformed

    public void addResult(Task t) {
        rbf.addResult(t);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable logTable;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JButton resultsBrowserButton;
    // End of variables declaration//GEN-END:variables

}
