/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MixedOptionPanel.java
 *
 * Created on Mar 29, 2011, 10:12:18 PM
 */

package pikater.gui.java.improved;

import com.sun.xml.internal.bind.v2.runtime.unmarshaller.IntArrayData;
import java.awt.Component;
import pikater.ontology.messages.Option;

/**
 *
 * @author martin
 */
public class MixedOptionPanel extends javax.swing.JPanel {

    /** Creates new form MixedOptionPanel */
    public MixedOptionPanel() {
        initComponents();
    }

    public boolean isDefault() {
        return defaultRadio.isSelected();
    }

    public boolean isUserValue() {
        return manualRadio.isSelected();
    }

    public boolean isAutomatic() {
        return autoRadio.isSelected();
    }

    public String getUserValue() {
        return userSpecifiedValueText.getText();
    }

    public String getLower() {
        return lowerSpinner.getValue().toString();
    }

    public String getUpper() {
        return upperSpinner.getValue().toString();
    }

    public String getSet() {
        return setText.getText();
    }

    public boolean isRange() {
        return intervalRadio.isSelected();
    }

    public boolean isSet() {
        return setRadio.isSelected();
    }

    public String getPattern() {
        return patternText.getText();
    }

    public int getTries() {
        return (Integer)triesSpinner.getValue();
    }

    public void setOption(Option o) {

        if (o.getMutable()) {
            autoRadio.setSelected(true);
            patternText.setText(o.getValue());
            if (o.getRange().getMax() != null && o.getRange().getMin() != null) {
                intervalRadio.setSelected(true);
                lowerSpinner.setValue(o.getRange().getMin().intValue());
                upperSpinner.setValue(o.getRange().getMax().intValue());
            }
            if (o.getIs_a_set()) {
                setRadio.setSelected(true);
                String set = "";

                for (int i = 0; i < o.getSet().size(); i++) {
                    set += o.getSet().get(i).toString();
                    if (i != o.getSet().size() - 1)
                        set += " ";
                }

                setText.setText(set);
            }
            triesSpinner.setValue(o.getNumber_of_values_to_try());
        }
        else {
            manualRadio.setSelected(true);
            userSpecifiedValueText.setText(o.getValue());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        defaultRadio = new javax.swing.JRadioButton();
        autoRadio = new javax.swing.JRadioButton();
        manualRadio = new javax.swing.JRadioButton();
        autoPanel = new javax.swing.JPanel();
        lowerSpinner = new javax.swing.JSpinner();
        setText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        upperSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        setRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        intervalRadio = new javax.swing.JRadioButton();
        patternText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        triesSpinner = new javax.swing.JSpinner();
        manualPanel = new javax.swing.JPanel();
        userSpecifiedValueText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        buttonGroup1.add(defaultRadio);
        defaultRadio.setSelected(true);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pikater/gui/java/improved/Bundle"); // NOI18N
        defaultRadio.setText(bundle.getString("KEEP DEFAULT VALUE")); // NOI18N

        buttonGroup1.add(autoRadio);
        autoRadio.setText(bundle.getString("THIS OPTION IS SET AUTOMATICALLY")); // NOI18N
        autoRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                autoRadioStateChanged(evt);
            }
        });

        buttonGroup1.add(manualRadio);
        manualRadio.setText(bundle.getString("USE MANUAL VALUE")); // NOI18N
        manualRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                manualRadioStateChanged(evt);
            }
        });

        autoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Automatic settings"));

        lowerSpinner.setEnabled(false);

        setText.setEnabled(false);

        jLabel1.setText(bundle.getString("OPTION PATTERN")); // NOI18N
        jLabel1.setEnabled(false);

        upperSpinner.setEnabled(false);

        jLabel3.setText(bundle.getString("TO")); // NOI18N
        jLabel3.setEnabled(false);

        buttonGroup2.add(setRadio);
        setRadio.setText(bundle.getString("SET")); // NOI18N
        setRadio.setEnabled(false);

        jLabel2.setText(bundle.getString("CHOOSE VALUES FROM")); // NOI18N
        jLabel2.setEnabled(false);

        buttonGroup2.add(intervalRadio);
        intervalRadio.setSelected(true);
        intervalRadio.setText(bundle.getString("INTERVAL")); // NOI18N
        intervalRadio.setEnabled(false);

        patternText.setEnabled(false);

        jLabel5.setText(bundle.getString("MAXIMUM TRIES")); // NOI18N
        jLabel5.setEnabled(false);

        triesSpinner.setEnabled(false);

        javax.swing.GroupLayout autoPanelLayout = new javax.swing.GroupLayout(autoPanel);
        autoPanel.setLayout(autoPanelLayout);
        autoPanelLayout.setHorizontalGroup(
            autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(autoPanelLayout.createSequentialGroup()
                        .addGroup(autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(intervalRadio)
                            .addComponent(setRadio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, autoPanelLayout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(patternText))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, autoPanelLayout.createSequentialGroup()
                                    .addComponent(lowerSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(upperSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(autoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(triesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        autoPanelLayout.setVerticalGroup(
            autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoPanelLayout.createSequentialGroup()
                .addGroup(autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patternText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intervalRadio)
                    .addComponent(lowerSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(upperSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setRadio)
                    .addComponent(setText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(triesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        manualPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Manual settings"));

        userSpecifiedValueText.setEnabled(false);
        userSpecifiedValueText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSpecifiedValueTextActionPerformed(evt);
            }
        });

        jLabel4.setText(bundle.getString("VALUE")); // NOI18N
        jLabel4.setEnabled(false);

        javax.swing.GroupLayout manualPanelLayout = new javax.swing.GroupLayout(manualPanel);
        manualPanel.setLayout(manualPanelLayout);
        manualPanelLayout.setHorizontalGroup(
            manualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manualPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userSpecifiedValueText, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );
        manualPanelLayout.setVerticalGroup(
            manualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manualPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(userSpecifiedValueText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manualRadio)
            .addComponent(autoRadio)
            .addComponent(defaultRadio)
            .addComponent(autoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manualPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(defaultRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manualRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manualPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userSpecifiedValueTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSpecifiedValueTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userSpecifiedValueTextActionPerformed

    private void autoRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_autoRadioStateChanged

        for (Component c : autoPanel.getComponents()) {
            c.setEnabled(autoRadio.isSelected());
        }        

    }//GEN-LAST:event_autoRadioStateChanged

    private void manualRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_manualRadioStateChanged

        for (Component c : manualPanel.getComponents()) {
            c.setEnabled(manualRadio.isSelected());
        }
        
    }//GEN-LAST:event_manualRadioStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel autoPanel;
    private javax.swing.JRadioButton autoRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton defaultRadio;
    private javax.swing.JRadioButton intervalRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner lowerSpinner;
    private javax.swing.JPanel manualPanel;
    private javax.swing.JRadioButton manualRadio;
    private javax.swing.JTextField patternText;
    private javax.swing.JRadioButton setRadio;
    private javax.swing.JTextField setText;
    private javax.swing.JSpinner triesSpinner;
    private javax.swing.JSpinner upperSpinner;
    private javax.swing.JTextField userSpecifiedValueText;
    // End of variables declaration//GEN-END:variables

}
