/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResultsFilterDialog.java
 *
 * Created on Mar 9, 2011, 12:56:39 AM
 */

package pikater.gui.java.improved;

import javax.swing.JCheckBox;
import pikater.ontology.messages.LoadResults;

/**
 *
 * @author Martin Pilat
 */
public class ResultsFilterDialog extends javax.swing.JDialog {


    private LoadResults lr = null;

    /** Creates new form ResultsFilterDialog */
    public ResultsFilterDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        maeLower = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        raeLower = new javax.swing.JSpinner();
        maeUpper = new javax.swing.JSpinner();
        raeUpper = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rrseUpper = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        rmseLower = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kappaUpper = new javax.swing.JSpinner();
        errorLower = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        rmseUpper = new javax.swing.JSpinner();
        kappaLower = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rrseLower = new javax.swing.JSpinner();
        errorUpper = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        errorChecbox = new javax.swing.JCheckBox();
        kappaCheckbox = new javax.swing.JCheckBox();
        rrseCheckbox = new javax.swing.JCheckBox();
        rmseCheckbox = new javax.swing.JCheckBox();
        raeCheckbox = new javax.swing.JCheckBox();
        maeCheckbox = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        dateBefore = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        dateAfter = new javax.swing.JSpinner();
        afterCheckbox = new javax.swing.JCheckBox();
        beforeCheckbox = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        testFile = new javax.swing.JTextField();
        trainFile = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        agentType = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        agentCheckbox = new javax.swing.JCheckBox();
        trainCheckbox = new javax.swing.JCheckBox();
        testCheckbox = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pikater/gui/java/improved/Strings"); // NOI18N
        jButton1.setText(bundle.getString("OK")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ERROR_MEASUREMENTS"))); // NOI18N

        maeLower.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 1.0d, 0.01d));
        maeLower.setEnabled(false);

        jLabel14.setText(bundle.getString("RAE")); // NOI18N

        jLabel11.setText(bundle.getString("RMSE")); // NOI18N

        jLabel3.setText(bundle.getString("<=")); // NOI18N

        raeLower.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 1.0d, 0.01d));
        raeLower.setEnabled(false);

        maeUpper.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 1.0d, 0.01d));
        maeUpper.setEnabled(false);

        raeUpper.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 1.0d, 0.01d));
        raeUpper.setEnabled(false);

        jLabel1.setText(bundle.getString("<=")); // NOI18N

        jLabel10.setText(bundle.getString("<=")); // NOI18N

        jLabel2.setText(bundle.getString("ERROR")); // NOI18N

        jLabel15.setText(bundle.getString("<=")); // NOI18N

        rrseUpper.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 1.0d, 0.01d));
        rrseUpper.setEnabled(false);

        jLabel7.setText(bundle.getString("<=")); // NOI18N

        rmseLower.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 1.0d, 0.01d));
        rmseLower.setEnabled(false);

        jLabel12.setText(bundle.getString("<=")); // NOI18N

        jLabel9.setText(bundle.getString("<=")); // NOI18N

        jLabel6.setText(bundle.getString("<=")); // NOI18N

        jLabel8.setText(bundle.getString("RRSE")); // NOI18N

        jLabel5.setText(bundle.getString("KAPPA")); // NOI18N

        kappaUpper.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 1.0d, 0.01d));
        kappaUpper.setEnabled(false);

        errorLower.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 1.0d, 0.01d));
        errorLower.setEnabled(false);

        jLabel18.setText(bundle.getString("MAE")); // NOI18N

        rmseUpper.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 1.0d, 0.01d));
        rmseUpper.setEnabled(false);

        kappaLower.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 1.0d, 0.01d));
        kappaLower.setEnabled(false);

        jLabel17.setText(bundle.getString("<=")); // NOI18N

        jLabel4.setText(bundle.getString("<=")); // NOI18N

        jLabel13.setText(bundle.getString("<=")); // NOI18N

        rrseLower.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 1.0d, 0.01d));
        rrseLower.setEnabled(false);

        errorUpper.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 1.0d, 0.01d));
        errorUpper.setEnabled(false);

        jLabel16.setText(bundle.getString("<=")); // NOI18N

        errorChecbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                errorChecboxStateChanged(evt);
            }
        });

        kappaCheckbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                kappaCheckboxStateChanged(evt);
            }
        });

        rrseCheckbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rrseCheckboxStateChanged(evt);
            }
        });

        rmseCheckbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rmseCheckboxStateChanged(evt);
            }
        });

        raeCheckbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                raeCheckboxStateChanged(evt);
            }
        });

        maeCheckbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                maeCheckboxStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(raeLower, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(maeLower, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(errorLower, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rrseLower, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kappaLower, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rmseLower, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel18)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maeUpper, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kappaUpper, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorUpper, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rrseUpper, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rmseUpper, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raeUpper, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rmseCheckbox, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(raeCheckbox, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(maeCheckbox, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(errorChecbox)
                    .addComponent(kappaCheckbox)
                    .addComponent(rrseCheckbox))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(errorLower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(kappaLower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(rrseLower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rmseLower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(raeLower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(maeLower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(errorUpper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(errorChecbox)
                                        .addGap(5, 5, 5)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(kappaCheckbox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rrseCheckbox))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(kappaUpper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(rrseUpper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(rmseUpper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(raeUpper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(maeUpper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(rmseCheckbox)
                                        .addGap(4, 4, 4)
                                        .addComponent(raeCheckbox)
                                        .addGap(5, 5, 5)
                                        .addComponent(maeCheckbox)))))
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel17)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("DATE_TIME"))); // NOI18N

        jLabel20.setText(bundle.getString("BEFORE")); // NOI18N

        dateBefore.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));
        dateBefore.setEnabled(false);

        jLabel19.setText(bundle.getString("AFTER")); // NOI18N

        dateAfter.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));
        dateAfter.setEnabled(false);

        afterCheckbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                afterCheckboxStateChanged(evt);
            }
        });

        beforeCheckbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                beforeCheckboxStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateBefore, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(dateAfter, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(afterCheckbox)
                    .addComponent(beforeCheckbox))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(afterCheckbox, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateAfter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(beforeCheckbox)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateBefore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("AGENT_FILES"))); // NOI18N

        testFile.setText(null);
        testFile.setEnabled(false);

        trainFile.setText(null);
        trainFile.setEnabled(false);

        jLabel22.setText(bundle.getString("TRAINING FILE")); // NOI18N

        jLabel21.setText(bundle.getString("AGENT TYPE")); // NOI18N

        agentType.setText(null);
        agentType.setEnabled(false);

        jLabel23.setText(bundle.getString("TESTING FILE")); // NOI18N

        agentCheckbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                agentCheckboxStateChanged(evt);
            }
        });

        trainCheckbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                trainCheckboxStateChanged(evt);
            }
        });

        testCheckbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                testCheckboxStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(testFile)
                    .addComponent(trainFile)
                    .addComponent(agentType, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trainCheckbox)
                    .addComponent(agentCheckbox)
                    .addComponent(testCheckbox))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(agentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(trainFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(testFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(trainCheckbox))
                            .addComponent(agentCheckbox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(testCheckbox)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText(bundle.getString("CANCEL")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        lr = new LoadResults();

        if (agentCheckbox.isSelected())
            lr.setAgentType(agentType.getText());
        if (trainCheckbox.isSelected())
            lr.setDataFile(trainFile.getText());
        if (testCheckbox.isSelected())
            lr.setTestFile(testFile.getText());

        if (errorChecbox.isSelected()) {
            lr.setErrorLower((Double)errorLower.getValue());
            lr.setErrorUpper((Double)errorUpper.getValue());
        }
        if (kappaCheckbox.isSelected()) {
            lr.setKappaLower((Double)kappaLower.getValue());
            lr.setKappaUpper((Double)kappaUpper.getValue());
        }
        if (maeCheckbox.isSelected()) {
            lr.setMaeLower((Double)maeLower.getValue());
            lr.setMaeUpper((Double)maeUpper.getValue());
        }
        if (rmseCheckbox.isSelected()) {
            lr.setMseLower((Double)rmseLower.getValue());
            lr.setMseUpper((Double)rmseUpper.getValue());
        }
        if (raeCheckbox.isSelected()) {
            lr.setRaeLower((Double)raeLower.getValue());
            lr.setRaeUpper((Double)raeUpper.getValue());
        }
        if (rrseCheckbox.isSelected()) {
            lr.setRrseLower((Double)rrseLower.getValue());
            lr.setRrseUpper((Double)rrseUpper.getValue());
        }

        if (afterCheckbox.isSelected())
            lr.setStartDate(dateAfter.getValue().toString());
        if (beforeCheckbox.isSelected())
            lr.setEndDate(dateBefore.getValue().toString());

        this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        lr = null;

        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void errorChecboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_errorChecboxStateChanged
        errorLower.setEnabled(((JCheckBox)evt.getSource()).isSelected());
        errorUpper.setEnabled(((JCheckBox)evt.getSource()).isSelected());
    }//GEN-LAST:event_errorChecboxStateChanged

    private void kappaCheckboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_kappaCheckboxStateChanged
        kappaLower.setEnabled(((JCheckBox)evt.getSource()).isSelected());
        kappaUpper.setEnabled(((JCheckBox)evt.getSource()).isSelected());
    }//GEN-LAST:event_kappaCheckboxStateChanged

    private void rrseCheckboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rrseCheckboxStateChanged
        rrseLower.setEnabled(((JCheckBox)evt.getSource()).isSelected());
        rrseUpper.setEnabled(((JCheckBox)evt.getSource()).isSelected());
    }//GEN-LAST:event_rrseCheckboxStateChanged

    private void rmseCheckboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rmseCheckboxStateChanged
        rmseLower.setEnabled(((JCheckBox)evt.getSource()).isSelected());
        rmseUpper.setEnabled(((JCheckBox)evt.getSource()).isSelected());
    }//GEN-LAST:event_rmseCheckboxStateChanged

    private void raeCheckboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_raeCheckboxStateChanged
        raeLower.setEnabled(((JCheckBox)evt.getSource()).isSelected());
        raeUpper.setEnabled(((JCheckBox)evt.getSource()).isSelected());
    }//GEN-LAST:event_raeCheckboxStateChanged

    private void maeCheckboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_maeCheckboxStateChanged
        maeLower.setEnabled(((JCheckBox)evt.getSource()).isSelected());
        maeUpper.setEnabled(((JCheckBox)evt.getSource()).isSelected());
    }//GEN-LAST:event_maeCheckboxStateChanged

    private void afterCheckboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_afterCheckboxStateChanged
        dateAfter.setEnabled(((JCheckBox)evt.getSource()).isSelected());
    }//GEN-LAST:event_afterCheckboxStateChanged

    private void beforeCheckboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_beforeCheckboxStateChanged
        dateBefore.setEnabled(((JCheckBox)evt.getSource()).isSelected());
    }//GEN-LAST:event_beforeCheckboxStateChanged

    private void agentCheckboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_agentCheckboxStateChanged
        agentType.setEnabled(((JCheckBox)evt.getSource()).isSelected());
    }//GEN-LAST:event_agentCheckboxStateChanged

    private void trainCheckboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_trainCheckboxStateChanged
        trainFile.setEnabled(((JCheckBox)evt.getSource()).isSelected());
    }//GEN-LAST:event_trainCheckboxStateChanged

    private void testCheckboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_testCheckboxStateChanged
        testFile.setEnabled(((JCheckBox)evt.getSource()).isSelected());
    }//GEN-LAST:event_testCheckboxStateChanged

    
    public LoadResults getFilter() {
        return lr;
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ResultsFilterDialog dialog = new ResultsFilterDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox afterCheckbox;
    private javax.swing.JCheckBox agentCheckbox;
    private javax.swing.JTextField agentType;
    private javax.swing.JCheckBox beforeCheckbox;
    private javax.swing.JSpinner dateAfter;
    private javax.swing.JSpinner dateBefore;
    private javax.swing.JCheckBox errorChecbox;
    private javax.swing.JSpinner errorLower;
    private javax.swing.JSpinner errorUpper;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox kappaCheckbox;
    private javax.swing.JSpinner kappaLower;
    private javax.swing.JSpinner kappaUpper;
    private javax.swing.JCheckBox maeCheckbox;
    private javax.swing.JSpinner maeLower;
    private javax.swing.JSpinner maeUpper;
    private javax.swing.JCheckBox raeCheckbox;
    private javax.swing.JSpinner raeLower;
    private javax.swing.JSpinner raeUpper;
    private javax.swing.JCheckBox rmseCheckbox;
    private javax.swing.JSpinner rmseLower;
    private javax.swing.JSpinner rmseUpper;
    private javax.swing.JCheckBox rrseCheckbox;
    private javax.swing.JSpinner rrseLower;
    private javax.swing.JSpinner rrseUpper;
    private javax.swing.JCheckBox testCheckbox;
    private javax.swing.JTextField testFile;
    private javax.swing.JCheckBox trainCheckbox;
    private javax.swing.JTextField trainFile;
    // End of variables declaration//GEN-END:variables

}
